command:
  - python3.9
  - ${program}
  - ${args_no_boolean_flags}
entity: flair
method: random
name: IQL
program: algorithms/iql.py
project: unifloral

parameters:
  # --- Experiment ---
  seed:
    values: [0, 1, 2, 3, 4]
  dataset:
    values:
      - halfcheetah-medium-v2
  algorithm:
    value: iql
  num_updates:
    value: 1_000_000
  eval_interval:
    value: 2500
  eval_workers:
    value: 8
  eval_final_episodes:
    value: 1000

  # --- Logging ---
  log:
    value: true
  wandb_project:
    value: unifloral
  wandb_team:
    value: flair
  wandb_group:
    value: debug

  # --- Generic optimization ---
  lr:
    value: 0.0003
  batch_size:
    value: 256
  gamma:
    value: 0.99
  polyak_step_size:
    value: 0.005

  # --- IQL specific ---
  beta:
    values: [0.5, 3.0, 10.0]
  iql_tau:
    values: [0.5, 0.7, 0.9]
  exp_adv_clip:
    value: 100.0
